name: CMake Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Клонировать репозиторий
      uses: actions/checkout@v3

    - name: Установить зависимости
      run: sudo apt-get update && sudo apt-get install -y cmake g++

    - name: Создать директорию сборки
      run: mkdir build

    - name: Сконфигурировать проект
      run: cmake -S . -B build

    - name: Собрать проект
      run: cmake --build build
